language: python
addons:
  apt:
    packages:
      - python-pygments
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.49/hugo_0.49_Linux-64bit.deb
  - sudo dpkg -i hugo_0.49_Linux-64bit.deb
script:
  - hugo
branches:
  only:
    - master
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: docs
after_success:
  - cd docs && hugo && mv docs/* .
