language: python
addons:
  apt:
    packages:
      - python-pygments
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.49/hugo_0.49_Linux-64bit.deb
  - sudo dpkg -i hugo_0.49_Linux-64bit.deb
script:
  - hugo
branches:
  only:
    - source
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: master
  on:
    branch: source
  local-dir: public
after_success:
  - cd public && hugo && mv public/* .
